# Min target
platform :ios, '11.0'

# Pod install settings
# Configured for using separate projects (more performant)
install! 'cocoapods',
generate_multiple_pod_projects: true,
incremental_installation: true
use_modular_headers!

# Open Source Cocoapods
source 'https://cdn.cocoapods.org'
target 'random-swift_Example' do
  pod 'random-swift', :path => '../'

  target 'random-swift_Tests' do
    inherit! :search_paths
    
  end
end
