# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12
language: swift
# cache: cocoapods
podfile: Projects/CocoapodsExample/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Projects/CocoapodsExample
script:
# run swift-pm compatibility tests
- echo "**** STARTING SPM TESTS *****"
- cd $TRAVIS_BUILD_DIR && sh ./scripts/swift-test
# run cococoapod compatibility tests
- echo "**** STARTING COCOAPODS TESTS *****"
- pod lib lint --verbose
