#!/bin/bash

# build using xcodebuild
 xcodebuild -workspace random-swift.xcworkspace \
  -scheme random-swift test \
  -sdk iphonesimulator \
  -destination 'platform=iOS Simulator,name=iPhone 11 Pro'