name: Generate Jazzy Docs

on: 
  release:
    types: [published]

jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Jazzy Docs
      uses: Steven0351/publish-jazzy-docs@v1.1.2  
      with:
        personal_access_token: ${{ secrets.REPO_SECRET }}
        args: "--min-acl public --author GigabiteLabs"
